# Generated by Django 5.2 on 2025-04-19 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('subject', models.CharField(choices=[('math', 'Riyaziyyat'), ('literature', 'Ədəbiyyat'), ('science', 'Elm'), ('history', 'Tarix')], max_length=20)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Döyüşçü', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=100)),
                ('analytic_power', models.IntegerField(default=1)),
                ('quick_think', models.IntegerField(default=1)),
                ('word_mastery', models.IntegerField(default=1)),
                ('research_skill', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.question')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions', models.ManyToManyField(to='battles.question')),
                ('warrior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battles.warrior')),
            ],
        ),
    ]
